### ISSUE TITLE
Toolbar icons are misaligned on demo page in Firefox

### ISSUE THREAD

**Issue by JeffJacobson** [skeate/Leaflet.buffer#10]
When viewing the [demo page](http://skeate.github.io/Leaflet.buffer/) in Firefox 35.0.1 the toolbar icons are misaligned. (It looked fine in Chrome, though.)

![2015-02-26 11_54_26-leaflet buffer by skeate](https://cloud.githubusercontent.com/assets/713754/6400527/4dec8e58-bdae-11e4-8023-2d4cce9dc73c.png)

**Comment by JeffJacobson** [comment]
FYI, just upgraded to Firefox 36.0 and the issue is still there.

**Comment by skeate** [comment]
Are you on Windows by chance? Just tried it in Firefox 36 in both OSX and Arch Linux and didn't see the issue.

**Comment by skeate** [comment]
Might also be a retina issue...

**Comment by JeffJacobson** [comment]
Yes, I am on Windows 7.

**Comment by JeffJacobson** [comment]
> Might also be a retina issue...

One of my monitors is a Dell U2713HM, resolution 2560 x 1440. The font size in Windows is set to "Medium 125%".

I am also seeing the misaligned toolbar icons in IE 11.

**Comment by skeate** [comment]
Just checked on my phone and it does the same thing so I'm pretty sure it's a DPI issue. Will check it out

**Comment by skeate** [comment]
Can you check [the demo site](http://skeate.github.io/Leaflet.buffer/) again? Pushed a fix there, seems to have fixed it on my phone, want to be sure it's fixed for you also before pushing here.

**Comment by JeffJacobson** [comment]
Yes, it's now working for me. Thanks.

**Comment by skeate** [comment]
Fixed in 78ef559662325ffcdcdc41ed24372b647eb112ed
