### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by pere** [skeate/Leaflet.buffer#15]
Looks a nice plugin, is a pity that not all necessary files are included and organized on the right folders...I had to download JSTS, I am still not able to find javascript.util.js (if you google around you get multiple results, of course)... when i run example, i get error 'Uncaught SyntaxError: Unexpected reserved word' on jsts.js line 1, that is 'import './Array'....

 some help would be appreciated

**Comment by danielxiong** [comment]
I have the same question. I don't know where to find the required files:
javascript.util.js
jsts.js

**Comment by fgarzonhz** [comment]
Hi every body, the jsts.js is a special js. you can find that file by google, then you Will enter in git repository, in that repository you will found the jsts.js minimized. Now the utility is similar case.

Frank

Enviado de Samsung Mobile


-------- Mensaje original --------
De: danielxiong
Fecha:21/01/2017 07:50 PM (GMT-05:00)
Para: "skeate/Leaflet.buffer"
Cc: Subscribed
Asunto: Re: [skeate/Leaflet.buffer] Installation process (#15)


I have the same question. I don't know where to find the required files:
javascript.util.js
jsts.js

-

**Comment by danielxiong** [comment]
thanks @fgarzonhz !
finally I found the jsts library with your inspiration.
[https://github.com/dlowther/jsts](url)

**Comment by skeate** [comment]
Hi pere and danielxiong!

Sorry this has been kind of dead for a while. I've just gone through and updated it a bit, mostly around the build process. It now packages _everything_ (including the relevant parts of JSTS!) into one file, which can be found at dist/leaflet.buffer.min.js. Hope this helps!
