### ISSUE TITLE
Buffer is oval-shaped when drawn around circle shape and separate_buffer = true

### ISSUE THREAD

**Issue by jacksonarcher** [skeate/Leaflet.buffer#16]
The buffer over the circle tool draws it in an oval shape, but only when separate_buffer = true. When separate_buffer = false, the circle expands into a larger circle.
![radius](https://cloud.githubusercontent.com/assets/21111521/17791741/838650c8-6562-11e6-9710-b67779d68261.png)

**Comment by skeate** [comment]
Thanks! Since circles aren't officially in the GeoJSON spec, it was actually trying to expand out from the center point. Not sure why JSTS makes that into an oval, but it's fixed now. Sorry for the delay!
