### ISSUE TITLE
NPM Package wont import

### ISSUE THREAD

**Issue by JonathanWilkins** [skeate/Leaflet.buffer#68]
I tried import your package as an ES6 module, but it kept failing in webpack.
Had a dig in your package.json  and your main property was index.js
Changed this  
"main": "index.js" 
to 
"main": "dist/leaflet.buffer.min.js"
and all is working.

Thanks for the awesome plugin.

**Comment by skeate** [comment]
Closed by #69

**Comment by skeate** [comment]
Fixed version published as 0.3.1
